// components/ux/checkout/data.ts
// Static option lists for the price → WhatsApp checkout panel.
// Kept here (not in dict) because brand/app names don't translate.

export type CheckoutOption = { value: string; label: string };

export const TV_BRANDS: CheckoutOption[] = [
  { value: "samsung",      label: "Samsung Smart TV" },
  { value: "lg",           label: "LG Smart TV (webOS)" },
  { value: "sony",         label: "Sony Bravia / Google TV" },
  { value: "hisense",      label: "Hisense VIDAA" },
  { value: "tcl",          label: "TCL (Google/Android TV)" },
  { value: "philips",      label: "Philips Smart TV" },
  { value: "panasonic",    label: "Panasonic Smart TV" },
  { value: "loewe",        label: "Loewe" },
  { value: "finlux",       label: "Finlux" },
  { value: "sharp",        label: "Sharp Smart TV" },
  { value: "toshiba",      label: "Toshiba Smart TV" },
  { value: "vestel",       label: "Vestel / Vestfrost" },
  { value: "skyworth",     label: "Skyworth" },
  { value: "firestick",    label: "Amazon Fire Stick / Fire TV" },
  { value: "apple-tv",     label: "Apple TV" },
  { value: "nvidia-shield",label: "Nvidia Shield" },
  { value: "chromecast",   label: "Chromecast with Google TV" },
  { value: "roku",         label: "Roku" },
  { value: "xiaomi",       label: "Xiaomi Mi Box / Mi Stick" },
  { value: "formuler",     label: "Formuler Z (Z8/Z10/Z11)" },
  { value: "mag",          label: "MAG (Infomir)" },
  { value: "enigma2",      label: "Enigma2 (Dreambox / VU+ / Zgemma)" },
  { value: "buzztv",       label: "BuzzTV" },
  { value: "android-tv",   label: "Android TV Box (generic)" },
  { value: "android-phone",label: "Android Phone / Tablet" },
  { value: "iphone-ipad",  label: "iPhone / iPad" },
  { value: "pc-mac",       label: "PC / Mac (browser)" },
  { value: "smart-tv-other", label: "Other Smart TV" },
  { value: "dont-know",    label: "I'm not sure yet" },
  { value: "other",        label: "Other (specify)" },
];

export const IPTV_APPS: CheckoutOption[] = [
  { value: "ibo-player",     label: "IBO Player" },
  { value: "ibo-pro",        label: "IBO Pro Player" },
  { value: "siptv",          label: "SIPTV / Smart IPTV" },
  { value: "smarters-pro",   label: "IPTV Smarters Pro" },
  { value: "smarters-lite",  label: "IPTV Smarters Lite" },
  { value: "tivimate",       label: "TiviMate" },
  { value: "flix-iptv",      label: "Flix IPTV" },
  { value: "net-iptv",       label: "Net IPTV" },
  { value: "perfect-player", label: "Perfect Player" },
  { value: "gse",            label: "GSE Smart IPTV" },
  { value: "xciptv",         label: "XCIPTV" },
  { value: "duplex",         label: "Duplex IPTV" },
  { value: "ott-navigator",  label: "OTT Navigator" },
  { value: "kodi",           label: "Kodi" },
  { value: "vlc",            label: "VLC" },
  { value: "mx-player",      label: "MX Player" },
  { value: "stalker",        label: "Stalker Player (MAG)" },
  { value: "myiptv",         label: "MyIPTV Player" },
  { value: "progtv",         label: "ProgDVB / ProgTV" },
  { value: "stbemu",         label: "STB Emulator" },
  { value: "televizo",       label: "Televizo" },
  { value: "aurora",         label: "Aurora IPTV" },
  { value: "lazy-iptv",      label: "Lazy IPTV" },
  { value: "dont-know",      label: "I don't know yet — please advise" },
  { value: "other",          label: "Other (specify)" },
];
